openshift/csi-driver-manila-operator

cmd/manager/main.go, deploy/olm-catalog/csi-driver-manila-operator/0.0.1/csi-driver-manila-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/csi-driver-manila-operator/csi-driver-manila-operator.package.yaml, go.mod, pkg/apis/addtoscheme_manilacsi_v1alpha1.go, pkg/controller/add_manilacsi.go, pkg/controller/manilacsi/manila_controllerplugin.go, pkg/controller/manilacsi/manila_controllerplugin_rbac.go, pkg/controller/manilacsi/manila_credentials.go, pkg/controller/manilacsi/manila_csidriver.go, pkg/controller/manilacsi/manila_nodeplugin.go, pkg/controller/manilacsi/manila_nodeplugin_rbac.go, pkg/controller/manilacsi/manila_service.go, pkg/controller/manilacsi/manilacsi_controller.go, pkg/controller/manilacsi/nfs_nodeplugin.go, pkg/controller/manilacsi/nfs_nodeplugin_rbac.go
Generated by `operator-sdk generate csv --csv-version 0.0.1`
Also changed "github.com/Fedosin" => "github.com/openshift"
=> Generate OLM catalog manifests

build/Dockerfile.openshift, build/Dockerfile.openshift.ci
This patch adds the required label `com.redhat.delivery.appregistry=true` and copies OLM catalog files to /manifests
=> Update Dockerfiles for OpenShift

deploy/olm-catalog/csi-driver-manila-operator/0.0.1/csi-driver-manila-operator.v0.0.1.clusterserviceversion.yaml, deploy/operator.yaml, pkg/controller/manilacsi/manila_controllerplugin.go, pkg/controller/manilacsi/manila_images.go, pkg/controller/manilacsi/manila_nodeplugin.go, pkg/controller/manilacsi/nfs_nodeplugin.go
This commit adds new env variables to the operator deployment that allow to set alternative images for the components.
=> Allow to redefine container images

README.md, bundle/manifests/csi-driver-manila-operator.v0.0.1.clusterserviceversion.yaml, deploy/crds/csi.openshift.io_v1alpha1_maniladriver_cr.yaml, deploy/namespace.yaml, deploy/operator.yaml, deploy/role.yaml, deploy/role_binding.yaml, deploy/service_account.yaml, examples/nfs/dynamic-provisioning/storageclass.yaml, examples/nfs/secrets.yaml, examples/nfs/snapshot/snapshotclass.yaml, examples/nfs/static-provisioning/preprovisioned-pvc.yaml, pkg/controller/maniladriver/credentials_request.go, pkg/controller/maniladriver/manila_controllerplugin.go, pkg/controller/maniladriver/manila_controllerplugin_rbac.go, pkg/controller/maniladriver/manila_credentials.go, pkg/controller/maniladriver/manila_csidriver.go, pkg/controller/maniladriver/manila_driver_namespace.go, pkg/controller/maniladriver/manila_nodeplugin.go, pkg/controller/maniladriver/manila_nodeplugin_rbac.go, pkg/controller/maniladriver/manila_scc.go, pkg/controller/maniladriver/manila_service.go, pkg/controller/maniladriver/manila_storageclasses.go, pkg/controller/maniladriver/maniladriver_controller.go, pkg/controller/maniladriver/nfs_nodeplugin.go, pkg/controller/maniladriver/nfs_nodeplugin_rbac.go
By default now Manila operator lives in "openshift-manila-csi-driver-operator" and all the driver's components are located in "openshift-manila-csi-driver".
Previously they were in "manila-csi".
=> Bug 1837210: Separate operator and driver namespaces

examples/nfs/dynamic-provisioning/pod.yaml, examples/nfs/static-provisioning/pod.yaml
gcr.io/hello-minikube-zero-install/hello-node doesn't exist anymore,
we started using more stable docker.io/library/nginx for example
pods.
=> Change image for example pods

bundle/manifests/csi-driver-manila-operator.v4.5.0.clusterserviceversion.yaml, version/version.go
This commit:
1. Changes Operator version from 0.0.1 to 4.5.0 to comply with OpenShift requirements.
2. Sets capabilities to Seamless Upgrades.
3. Adds aos-storage-staff to the list of maintainers.
4. Bumps minKubeVersion to 1.17.0
=> Bug 1835654: Update CSV manifest

bundle/manifests/csi-driver-manila-operator.v4.5.0.clusterserviceversion.yaml, deploy/operator.yaml
Now we use the "latest" tag, which also points at 4.5. But soon 4.6 will become the latest, and 4.5 manifests will be broken.
=> Use 4.5 images in the manifests

assets/controller.yaml, assets/controller_sa.yaml, assets/node.yaml, assets/node_nfs.yaml, assets/node_sa.yaml, assets/rbac/controller_privileged_binding.yaml, assets/rbac/node_privileged_binding.yaml, assets/rbac/provisioner_binding.yaml, assets/rbac/snapshotter_binding.yaml, manifests/09_credentials.yaml, pkg/controllers/manila/manila.go, pkg/controllers/secret/secretsync.go, pkg/generated/bindata.go, pkg/operator/starter.go, pkg/util/const.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go, vendor/modules.txt
Manila moves to openshift-manila-csi-driver to keep compatibility with old OLM-based operator. Make sure that all objects have the same objects and same selectors as the OLM-based ones, so the new operator can adopt OLM Deployment/DaemonSets.
@openshift/storage
=> Change operand namespace

pkg/controllers/manila/manila.go
`ManilaControllerAvailable` condition is set too early in the operator lifetime and often it can be the only one Available condition present, so CSO reports the whole Manila driver is Available.
In addition, this condition does not report anythig useful. There is a separate "Disabled" condition to report that Manila is not present and CSI driver presence is reported by `ManilaDriverControllerAvailable`/`NFSDriverControllerAvailable` conditions.
@openshift/storage
=> Remove ManilaControllerAvailable condition

assets/node.yaml, assets/node_nfs.yaml, pkg/generated/bindata.go
So masters and other tainted nodes can use PVCs.
=> Bug 1863056: Allow the driver to run on any node

manifests/05_clusterrole.yaml, pkg/operator/starter.go
Fixed sync of openshift-config/cloud-provider-config into the driver namespace and add the operator enough permissions to actually do that.
Sync RBAC from CSO here, because it has been tested more in CSO.
=> Bug 1867735: Fix sync of openshift-config/cloud-provider-config ConfigMap

pkg/controllers/manila/manila.go
Now, when we generate storageclass names we use a prefix followed by manila share type names. Unfortunately storageclass names can't contain uppercase characters, which is possible for manila share types. As a result of this, we get errors when deploying the driver.
To prevent the issue we preliminary convert manila share type names to lowercase.
=> Bug 1869504: base storageclass names on lower case

assets/controller.yaml, manifests/07_deployment.yaml, pkg/generated/bindata.go
This should allow the manilla controller to run on the master nodes. It still needs to be tested for confirmation.
=> Bug 1871999: Allow controller and DaemonSets to run on master nodes

pkg/controllers/secret/secretsync.go, pkg/operator/starter.go, pkg/util/const.go
Since commit 44d79d3281, we are no longer creating the CredentialsRequest in this operator, but we're relying on CVO to create it. However, we were previously creating 2 CRs: 1 in this operator (for the CSI driver) and another one in CSO (for the this operator itself).
Since now we can only create CRs in CVO, instead of creating 2 different CRs like we were doing before, we're creating only 1 and using it for both this operator and the CSI driver.
CC @openshift/storage
=> Bug 1868339:     Use the CredentialsRequest created by CVO

assets/rbac/provisioner_role.yaml, pkg/generated/bindata.go
As result of the external-provisioner rebase to v2.0.0, it now needs VolumeAttachment read-only access.
=> Bug 1876791: Update RBAC of the external-provisioner

pkg/controller/maniladriver/manila_storageclasses.go
Now, when we generate storageclass names we use a prefix followed by manila share type names. Unfortunately storageclass names can't contain uppercase characters, which is possible for manila share types. As a result of this, we get errors when deploying the driver.
To prevent the issue we preliminary convert manila share type names to lowercase.
=> Bug 1869590: base storageclass names on lower case

pkg/controller/maniladriver/nfs_nodeplugin.go
The NFS driver should use hostNetwork to use `clientAddr=<node IP address>` instead of (randomized) Pod IP address.
See https://bugzilla.redhat.com/show_bug.cgi?id=1878980.
@openshift/storage @Fedosin
=> Bug 1878980: Use hostNetwork for the NFS CSI driver

assets/controller.yaml, pkg/controllers/secret/secretsync.go, pkg/generated/bindata.go
This patch mounts custom ca cert bundle into the predifined location:
/etc/kubernetes/static-pod-resources/configmaps/cloud-config
And forces the driver's controller to take the bundle from this location only.
=> Bug 1880896: Replace cert authority path from clouds.yaml

assets/node.yaml, pkg/generated/bindata.go
See the BZ, we must update node plugin to reflect new cacert location moved in https://github.com/openshift/csi-driver-manila-operator/pull/64.
@Fedosin @openshift/storage, PTAL
=> Bug 1883018: Fix location of node plugin cacert file

assets/namespace.yaml, pkg/generated/bindata.go
This PR is a complement of https://github.com/openshift/cluster-storage-operator/pull/100.
The namespace used by Manila CSI driver is different from other CSI drivers (for backwards compatibility reasons), and it's created by the Manila operator (rather than CVO/CSO, as the other CSI drivers).
CC @openshift/storage
=> Bug 1894025: Add annotation to operand's namespace

pkg/controllers/manila/manila.go
Now when user doesn't have permissions to list share types, Manila returns 403 error, and the operator becomes Degraded blocking upgrades.
This commit prevents this situation and disables the operator if 403 error was returned.
=> Bug 1917587: disable Manila operator in case of 403 error

pkg/operator/starter.go
The informer must be started to be actually usable.
=> Bug 1918140: Fix sync of config.openshift.io informer

pkg/controllers/manila/openstack.go
Current timeout is set to 30 seconds, but sometimes Keystone is too slow to respond within this time, and the operator becomes degraded.
To mitigate this behavior we increase the timeout to 2 minutes.
=> Bug 1918716: increase Keystone timeout to 2 minutes

pkg/controllers/manila/manila.go, pkg/controllers/manila/openstack.go
This is a manual cherry-pick of #81 and #84.
The changes allow Manila operator to tolerate 403 and 404 errors, that would otherwise cause the operator and the whole cluster to enter a degraded state. We now disable the Manila operator on 403 and 404 errors.
This PR also add more debugging info.
=> [release-4.6] Bug 1918367: Make Manila operator more tolerant

assets/node.yaml, assets/node_nfs.yaml, pkg/generated/bindata.go
To speed up cluster upgrade by allowing more nodes to be updated
simultaneously.
=> Bug 1933184: Add maxUnavailable to DaemonSets

assets/rbac/kube_rbac_proxy_binding.yaml, assets/rbac/prometheus_role.yaml, assets/rbac/prometheus_rolebinding.yaml, assets/service.yaml, assets/servicemonitor.yaml, pkg/generated/bindata.go
Use the manila namespace instead of `openshift-cluster-csi-drivers`.
=> Bug 1949357: Fix namespace in metrics collection objects

assets/controller.yaml, assets/node.yaml, pkg/generated/bindata.go
This pull request explicitly set the imagePullPolicy to IfNotPresent
fixes  [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1947774)
=> Bug 1947774: fix imagePullPolicy to ifNotPresent 

assets/controller.yaml, pkg/generated/bindata.go, pkg/operator/starter.go
In https://github.com/kubernetes/cloud-provider-openstack/pull/1459 we added a possibility to append share metadata with cluster id specified by "--cluster-id" argument.
This commit starts using this feature in the operator.
=> Bug 1820238: add cluster id to share metadata

.gitignore, Dockerfile.test
Add a basic Dockerfile.test that was largely inspired by the one in the
Cinder CSI operator.
We also had to change the .gitignore to remove "*.text" entry.
Part of [OSASINFRA-2494](https://issues.redhat.com/browse/OSASINFRA-2494).
=> Create CI image for Manila CSI Operator testing

assets/volumesnapshotclass.yaml, pkg/operator/starter.go
This commit allows the operator to create a default volumesnapshotclass for Manila CSI driver.
=> Generate default volumesnapshotclass for Manila CSI driver

pkg/controllers/manila/openstack.go
Even though the proxy env vars are available
they are not used when attempting to connect
to the OSP clouds through the proxy. This commit
fixes the issue by ensuring those env vars are
used when available.
=> Bug 1960152: Use cluster Proxy when available

assets/namespace.yaml, pkg/operator/starter.go
The namespace must exist to compose correct RelatedObjects in CSO.
See https://github.com/openshift/cluster-storage-operator/pull/202 for details.
=> Bug 1991814: Move namespace creation to cluster-storage-operator

pkg/controllers/manila/manila.go
It's possible that for one reason or another we're unable to reach the
Manila endpoint. In the past we've tried to be smart and handled errors
differently, if it's a 404, a 403, or other types of errors. The
problem with this approach is that it's very easy to forget valid
failure cases. We've had a recent example with proxy setting not
correctly propagated to the Manila pod and degrading the cluster.
We should instead treat all failures to reach the Manila endpoint as
a non fatal error and disable the Manila operator instead of making the
cluster degraded.
This makes the Manila operator consistent with the EFS one.
=> Bug 2001620: Do not degrade cluster on failure to reach Manila

pkg/controllers/manila/openstack.go
Even though the proxy env vars are available
they are not used when attempting to connect
to the OSP clouds through the proxy. This commit
fixes the issue by ensuring those env vars are
used when available.
=> [release-4.6] Bug 2000097: Use cluster Proxy when available

pkg/controllers/manila/manila.go
It's possible that for one reason or another we're unable to reach the
Manila endpoint. In the past we've tried to be smart and handled errors
differently, if it's a 404, a 403, or other types of errors. The
problem with this approach is that it's very easy to forget valid
failure cases. We've had a recent example with proxy setting not
correctly propagated to the Manila pod and degrading the cluster.
We should instead treat all failures to reach the Manila endpoint as
a non fatal error and disable the Manila operator instead of making the
cluster degraded.
This makes the Manila operator consistent with the EFS one.
=> [release-4.6] Bug 2002556: Do not degrade cluster on failure to reach Manila

.ci-operator.yaml, build/Dockerfile.openshift, pkg/dependencymagnet/dependencymagnet.go
Reconciling with https://github.com/openshift/ocp-build-data/tree/5b89f5b601508a0bcc0399fd3f34b7aa2e86e90e/images/csi-driver-manila-operator.yml
Replaces https://github.com/openshift/csi-driver-manila-operator/pull/129
/cc @openshift/storage
=> Updating csi-driver-manila-operator images to be consistent with ART

pkg/controllers/manila/manila.go
It's possible that an operator creates a Manila share type containing "_"
characters in the name, which are invalid in the kubernetes context [1].
Instead of failing and workaround it on the OpenStack side (e.g., rename
the Share type name), this patch just normalize the storage class name
using the allowed format, maintaining the right "type" metadata to make
sure the CSI driver is able to resolve the share type capabilities when
a pvc is created.
Fixes #43
[1] https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
Signed-off-by: Francesco Pantano <fpantano@redhat.com>
=> Normalize the storage class name when ShareType has invalid characters

test/e2e/manifest.yaml
More tests could be run, let's just enable them in the e2e manifest.
=> ci: enable more tests

go.mod, go.sum, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go, vendor/modules.txt
**What this PR does / why we need it**:
This patch upgrades `github.com/prometheus/client_golang` to v1.11.1,
where the vulnerability has been fixed.
See the [Prometheus advisory](https://github.com/prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p)
This commit is the result of running:
```
go get github.com/prometheus/client_golang@v1.11.1 \
&& go mod tidy && go mod vendor
```
**Notes for the reviewer**:
One handy way to check that the version of `client_go` used for compiling contains the security patch, is to run `go mod vendor` and check that the `InstrumentRoundTripperCounter` method [contains a variadic `options` argument](https://github.com/prometheus/client_golang/compare/v1.11.0...v1.11.1#diff-7871a83741d29b5f29e3c47d1c284f948c258a0c6fc18895f0c2d4204cc46054R63). …
=> Bug 2067749: Address CVE-2022-21698

assets/controller.yaml
CVE-2016-2183
CVE-2016-6329
The default ciphers are not secure and are susceptible to a number of
different known vulnerabilities. This collection of ciphers should be
more secure and have no known vulnerabilities present.
Specific ciphers cribbed from https://github.com/openshift/cluster-machine-approver/commit/1f541e8a321ae57e1a8b1daf8c7890d96ae9e367
=> Bug 2090662: SWEET32: Improve TLS configuration for Kube RBAC Proxy

pkg/controllers/secret/secretsync.go, pkg/controllers/secret/secretsync_test.go
With this patch, application credentials found in the clouds.yaml file
are passed in the Manila secret
`openshift-manila-csi-driver/csi-manila-secrets`.
=> Bug 2083153: Fetch application credentials

assets/csidriver.yaml, manifests/07_deployment.yaml, pkg/controllers/manila/manila.go, pkg/controllers/secret/secretsync.go, pkg/operator/starter.go
The operator is now able to configure the CSIDriver object applying a
FsGroupPolicy value defined as input. csidriver.yaml is not a static resource
anymore and the manila driver operator manifest is updated to support this new
option.  The manila controller introduces some logic to dynamically refresh the
CSIDriver resource and, this pattern can be extended for any other option we'd
like to support in the future. The CSI_FSGROUP_POLICY option is defined as an
environment variable for the operator, and it's forced to None if the operator
doesn't make an explicit override.
Signed-off-by: Francesco Pantano <fpantano@redhat.com>
=> Expose CSI_FSGROUP_POLICY as an operator option

assets/volumesnapshotclass.yaml
The manila-csi snapshotter needs to have access to the manila provisioner secrets in order to create snapshots. 
Secrets [0]  are created within the `openshift-manila-csi-driver` namespace [1] and they should be referenced by
the `SnapshotVolumeClass`, which doesn't include them.
[0] https://github.com/openshift/csi-driver-manila-operator/blob/master/pkg/util/const.go#L7
[1] https://github.com/openshift/csi-driver-manila-operator/blob/master/pkg/util/const.go#L5
fixes #139
Signed-off-by: Francesco Pantano <fpantano@redhat.com>
=> Bug 2057637: Include secrets to VolumeSnapshotClass

pkg/controllers/manila/manila.go
Go 1.19 now formats the comments, which causes the verify job to fail after go is upgraded.
This commit is the result of running the following command with go 1.19:
go fmt ./pkg/...
=> Ensure files follow go 1.19 formatting

assets/node.yaml, assets/node_nfs.yaml
To support `mount -o context=XYZ`, /etc/selinux and /sys/fs/selinux from the host must be present in the CSI driver container.
Both Manila and NFS CSi driver containers are modified in this PR.
For @openshift/team-openstack folks, this mount option will be used by Kubernetes 1.26 (~4.13) when feature gate [`SELinuxMountReadWriteOncePod` is enabled](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1710-selinux-relabeling), i.e. as dev preview. I just want to be able to test it in OCP with all CSI drivers that we ship to make sure it works as we expect.
cc @openshift/storage
=> STOR-1078: Add hostPaths necessary for SELinux mounts

assets/controller.yaml, assets/node.yaml, assets/node_nfs.yaml
To support the workload partitioning we need to add the required annotations (openshift/enhancements#703).
=> OCPBUGS-8683: Add management workloads annotations

pkg/operator/starter.go
Add a secret informer for the secret that we store credentials in, `openshift-cluster-csi-drivers / manila-cloud-credentials`, like we already do for the Cinder CSI Driver Operator. As is the case there, this ensures our controllers will reload upon changes to the secret.
This is an alternative approach to #184 and not yet tested.
=> OCPBUGS-14049: Add secret informer

pkg/operator/starter.go
This reverts commit 705fb00702b19a7af5149ccbea1435b802632a57. The informers are not applied to the affected controller and have no effect. Revert the change to prevent confusion at a later date.
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
=> Revert "OCPBUGS-14049: Add secret informer"

pkg/controllers/manila/manila.go, pkg/controllers/manila/openstack.go, pkg/operator/starter.go
We are initialising an OpenStack client and storing it as an attribute of `ManilaController`. However, this takes the credentials at the time of client creation. These credentials can change over time, as a result of e.g. password rotation.
We opt to avoid caching the client, creating it each time we need it rather than once during creation of the controller instance. Given the sync interval, the overhead of this should be minimal.
=> OCPBUGS-14049: Don't cache OpenStack client

pkg/controllers/manila/openstack.go
This can be a helpful breadcrumb when debugging services.
Note that the version information ldflags are populated by [build-machinery-go](https://github.com/openshift/build-machinery-go), which provides e.g. the `build` makefile target.
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
=> Configure User Agent

assets/service.yaml
The selector was pointing to a non-existing pod and as a result the endpoint was empty. The controller app is named `openstack-manila-csi`.
=> OCPBUGS-9331: Fix selector for manila-csi-driver-controller-metrics service

assets/controller.yaml, assets/node.yaml
Some containers had duplicated resources requests. This patch cleans up the pods definitions and removes the duplicates.
=> NO-JIRA: Cleanup duplicated resources requests

assets/controller.yaml, assets/node.yaml
Add missing healthchecks to Manila CSI driver and node registrar pods, similar to what was done for Cinder CSI in https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/52 and https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/161.
=> OCPBUGS-29240: Add missing healthchecks

README.md
With the manila operator merge to csi-operator
this operator becomes obsolete. This commit
adds a warning about it.
=> NO-JIRA: Add warning about repository being obsolete
